FL/Models/Payment.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace FL.Models
{
	public class Payment
	{
		[Key]
		public int PaymentId { get; set; }

		public int FromAccountNumber { get; set; }

		public int AmountOfMoney { get; set; }

		public String Date { get; set; }
	}
}

FL/ViewModels/PaymentViewModel.cs
using FL.Models;

namespace FL.ViewModels
{
	public class PaymentViewModel
	{
		public Payment Payment { get; set; }

		public int TarifId { get; set; }
	}
}

FL/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using FL.Models;
using FL.Services;
using FL.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;


namespace FL.Controllers
{
	public class CommonController : Controller
	{
		private readonly DatabaseManager _dbDatabaseManager;
		private readonly PaymentController _paymentService;
		private readonly JobsController _jobsService;
		private readonly FreelancersController _freelancersController;

		public CommonController()
		{
			_dbDatabaseManager = new DatabaseManager();
			_paymentService = new PaymentController(_dbDatabaseManager);
			_jobsService = new JobsController(_dbDatabaseManager);
			_freelancersController = new FreelancersController(_dbDatabaseManager);
		}

		public ActionResult Index()
		{
			return View();
		}

		[HttpGet]
		public ActionResult Payment(int tarifId)
		{
			AvailableTarif tarif = _dbDatabaseManager.GetAvailableTarifById(tarifId);
			Payment payment = new Payment() { AmountOfMoney = tarif.Price };
			PaymentViewModel paymentViewModel = new PaymentViewModel()
			{
				Payment = payment,
				TarifId = tarif.AvailableTarifId,
			};
			return View("Payment", paymentViewModel);
		}

		[HttpPost]
		public ActionResult SubmitPayment(PaymentViewModel paymentViewModel)
		{
			User currentUser = _dbDatabaseManager.GetUserById(User.Identity.GetUserId());
			AvailableTarif tarif = _dbDatabaseManager.GetAvailableTarifById(paymentViewModel.TarifId);
			TarifSale sale = new TarifSale()
			{
				Buyer = currentUser,
				StartDate = DateTime.Now.ToString(),
				EndDate = DateTime.Now.AddDays(tarif.DurationDays).ToString(),
				Payment = paymentViewModel.Payment,
				Tarif = tarif,
			};

			bool result = _paymentService.PerformSaleOperation(sale);

			return View("PaymentResult", result);
		}

		[HttpGet]
		public ActionResult ApplyForTheJob(int jobId)
		{
			User currentUser = _dbDatabaseManager.GetUserById(User.Identity.GetUserId());
			Vacancy vacancy = _dbDatabaseManager.GetVacancyById(jobId);
			bool result = _jobsService.ApplyForTheJob(currentUser, vacancy);
			return View("ApplyForTheJobResultPage", result);
		}

		[HttpGet]
		public ActionResult GetFreelancers(string name = "")
		{
			IEnumerable<IdentityUser> freelancers = _freelancersController.GetFreelancersByName(name);
			return View("FreelancersList", freelancers);
		}
	}
}

FL/Views/Common/ApplyForTheJobResultPage.cshtml
@model bool

<h2>ApplyForTheJobResultPage</h2>

@if (Model)
{
	<h3>Apply succed!</h3>
}
else
{
	<h3>Apply failed.</h3>
}

FL/Views/Common/FreelancersList.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityUser> 

@{
    ViewBag.Title = "FreelancersList";
}

<h2>FreelancersList</h2>

<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.UserName)
		</th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.DisplayFor(modelItem => item.UserName)
			</td>
		</tr>
	}

</table>

FL/Views/Common/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

FL/Views/Common/Payment.cshtml
@model FL.ViewModels.PaymentViewModel

<h2>TarifPaymentPage</h2>


@using (Html.BeginForm("SubmitPayment", "Common", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Payment.FromAccountNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Payment.FromAccountNumber)
                @Html.ValidationMessageFor(model => model.Payment.FromAccountNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Payment.AmountOfMoney, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Payment.AmountOfMoney, new {@readonly = "readonly"})
            </div>
        </div>
		@Html.HiddenFor(model => model.TarifId)


	    <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FL/Views/Common/PaymentResult.cshtml
@model bool

@{
 ViewBag.Title = "PaymentResult";
}
<h2>TarifPaymentResult</h2>

@if (Model)
{
	<h3>Payment succed!</h3>
}
else
{
	<h3>Payment failed.</h3>
}